### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by ketevan-b** [structurizr/dotnet#100]
Hello
We have a lot of systems and a lot of connections between them, these systems are all located in one space, and when I want to add more connections - they don't bother me anymore. Goes to the next exception:
Structurizr.Api.StructurizrClientException
  HResult=0x80131500
  Message=There was an error putting the workspace: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
  Source=Structurizr.Client
  StackTrace:
   at Structurizr.Api.StructurizrClient.PutWorkspace(Int64 workspaceId, Workspace workspace)
   at C4.LibertyBank.Program.Main(String[] args) in C:\Users\ketevan.burjanadze\source\repos\C4\C4.LibertyBank\Program.cs:line 24

Inner Exception 1:
JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

Also the system can't load the lensscape diagram, it shows me the following message
![image](https://user-images.githubusercontent.com/61318524/199675602-fd3f1ee8-faa4-4fbe-a84e-b33fbfd74b0d.png)

 Can you help me?

**Comment by simonbrowndotje** [comment]
```
There was an error putting the workspace: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
```

This seems to suggest that an incorrect API URL was used, or that the Structurizr installation was temporarily unavailable. If this doesn't resolve itself, please do provide more information.

> Also the system can't load the lensscape diagram, it shows me the following message

You can click the "OK" button to render the diagram. But Structurizr is telling you that your diagram has too many elements and relationships. Not only will it be hard to read, it will be slow to render. So I'd suggest breaking up the diagram/workspace.
