### ISSUE TITLE
Default RankDirection not being serialized

### ISSUE THREAD

**Issue by SuprisingPlum** [structurizr/dotnet#103]
**Steps to reproduce**

1) Create new work space with C4 diagrams
2) Click on the diagram

**Expected Result**

Diagram appears and is clickable

**Actual Result**

Blank page appears like in the screenshot below

![image](https://user-images.githubusercontent.com/126168653/220912616-9c9996fc-b8d0-4c0b-9ca7-914af2c71956.png)

**Comment by simonbrowndotje** [comment]
The default value for RankDirection wasn't being serialized, and automatic layout was failing.

v1.1.1 is now available on Nuget, which should resolve your issue.

**Comment by SuprisingPlum** [comment]
Updated the Nuget package to v1.1.1 and tested. The diagrams are being displayed as expected. Thank you for the quick response and fix!
