### ISSUE TITLE
New build/deploy flow for NuGet?

### ISSUE THREAD

**Issue by coldacid** [structurizr/dotnet#15]
I hope I'm not stepping on your toes with this, but I took some time this weekend to see how to get NuGet packages built automatically for the Structurizr .NET assemblies, and I think I have something workable in my [new-build-script](/coldacid/structurizr-dotnet/tree/new-build-script) branch. It uses Appveyor instead of Travis CI to do builds, but handles build, test, and packaging properly. You can check out the build log and results at https://ci.appveyor.com/project/coldacid/structurizr-dotnet

The config for Appveyor uses git tags to determine the version to set, or relies on whatever version is in the .csproj files. The new style projects use a combination of `VersionPrefix` and `VersionSuffix` properties to determine the version for use in the assembly metadata as well as for NuGet packages, and this configuration will add a "pre-<githash>" suffix to non-tagged builds. It seems a bit jury-rigged since the `dotnet pack` CLI command doesn't properly handle version suffixes for project references and so has to use `dotnet msbuild` instead; however, the resulting packages have the correct version and reference metadata and should work well together.

This should be easily workable although the main version number and release notes will have to be updated in the .csproj files themselves for every release (the `ReleaseNotes` property before committing and tagging the release commit, and `VersionPrefix` immediately after so new builds don't get versions that would stick them as pre-release builds; this is why it's already set to 0.6.0 in the project files).

**Comment by simonbrowndotje** [comment]
Thanks, looks good and automating all of this was on my todo list anyway. :-) BTW, the Travis thing never really worked, mostly because of the dependencies on net45.
