### ISSUE TITLE
Missing dotnet reflection methods in Structurizr.Core-0.6.0 nuget package

### ISSUE THREAD

**Issue by merijndejonge** [structurizr/dotnet#21]
Hi,
I just upgraded the Structurizr nuget package in my project to version 0.6.0 (previous version I worked with was  0.4.0.1).  In this version, the reflection part no longer works, because (At least) the following reflection types seem to be missing:
* TypeBasedComponentFinderStrategy
* ExtendsClassTypeMatcher
I see that they are still present in the git repository, so either I'm doing something wrong, or something is wrong with the nuget package.

I checked that everything is working normally until version 0.5.1. So, the change has been in the latest release of Structurizr.

Any ideas what this can be?

**Comment by simonbrowndotje** [comment]
Apologies, I've not finished pushing everything to Nuget yet. You will have a couple of options once this is done ... Structurizr.Reflection and Structurizr.Cecil ... this is my todo list for today.

**Comment by simonbrowndotje** [comment]
The Structurizr.Reflection package has now just been published.

**Comment by merijndejonge** [comment]
Thanks, that solved the issue!
