### ISSUE TITLE
Should I commit json output files

### ISSUE THREAD

**Issue by tpluscode** [structurizr/dotnet#22]
Hi. Every time I run the app to publish the diagrams, a JSON files gets created. Is it intended to be committed to my repository? Or maybe it's possible not to have it created in the first place?

**Comment by simonbrowndotje** [comment]
It's up to you, that JSON file is the version that is pulled from the Structurizr API. You can disable this behaviour if you like -> https://github.com/structurizr/dotnet/blob/master/docs/api-client.md#1-getworkspace

**Comment by tpluscode** [comment]
Thanks
