### ISSUE TITLE
Anybody interested in a fluent interface for Structurizr.Core?

### ISSUE THREAD

**Issue by jrnail23** [structurizr/dotnet#28]
Since I have a personal affinity for DSLs, fluent interfaces, and the builder pattern, I figured I'd ask: would anyone be interested in using a fluent interface over the top of Structurizr.Core?

If so, I'd enjoy taking a swing at it.

**Comment by coldacid** [comment]
I'm certainly interested in how it might look.

**Comment by jrnail23** [comment]
@coldacid, I'll take a shot at something representative then I'll post it here.  To be clear, I don't necessarily think this needs to be a part of the main project or anything -- it might work better as a separate contrib thing.  API design can be pretty opinionated, so getting more than 2 devs to agree on something can be quite a daunting task.

**Comment by simonbrowndotje** [comment]
If you do this (and I think a separate repo is the way to go), let me know and I'll add a link to the project home page, so that other people can find it. 👍

**Comment by mario-d-s** [comment]
I'd love this. Please keep us posted and let me know if there's anything I can help with.
