### ISSUE TITLE
Crashes while building if Markdowns contain german or french special characters.

### ISSUE THREAD

**Issue by unejamardiani** [structurizr/dotnet#3]
Throws exception 401 not authorized if markdowns contain french or german special characters like ä, ö, ü, è.

**Comment by simonbrowndotje** [comment]
Thanks ... the fix for this has been pushed to GitHub. Do you need a new version of the Nuget package?

**Comment by unejamardiani** [comment]
Oh you're very quick thank you... no we stick to our workaround for now and update later thank you... I don't think it's the right place to ask but is there any function to export the architecture documentation to a html or pdf?
