### ISSUE TITLE
UsesComponent how to use correctly

### ISSUE THREAD

**Issue by Godgifu** [structurizr/dotnet#31]
Hello

I'm new to structurizr and try to etablish a relationship between a controller and a model.

This looks this way:

```
    [Component(Description = "Account controller", Technology = "C#")]
    [UsedByPerson("User", Description = "Uses")]
    public class AccountController : Controller
    {
        private readonly UserManager<CustomUser> _userManager;
    }
```

My model is CustomUser:

```
    [Component(Description = "Custom user model", Technology = "C#")]
    public class CustomUser : IdentityUser
    {
        public string FirstName { get; set; }
    }
```

In this case I have no chance to use UsesComponent, if I want to show the relationship, I need to use:

```
        [UsesComponent("Uses model", Technology = "C#")]
        private CustomUser userForDocumentationOnly = null; 
```
in the controller. This seems very ugly and I'm sure, I'm doing something wrong. Whats the correct approach?

Thanks

**Comment by simonbrowndotje** [comment]
The question to ask here is whether you really see the ```CustomUser``` class as a "component". If it's just a data structure (i.e. a plain old C# object, with no interesting behaviour), then I wouldn't necessarily view it as a component.
