### ISSUE TITLE
unable to add reflection package version 0.7.0

### ISSUE THREAD

**Issue by JohnnyShep** [structurizr/dotnet#33]
Attempting to gather dependency information for package 'Structurizr.Reflection.0.7.0' with respect to project '*********************', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 1.08 sec
Attempting to resolve dependencies for package 'Structurizr.Reflection.0.7.0' with DependencyBehavior 'Lowest'
Unable to resolve dependencies. 'Newtonsoft.Json 11.0.2' is not compatible with 'Structurizr.Core 0.7.0 constraint: Newtonsoft.Json (>= 10.0.3)'.

**Comment by simonbrowndotje** [comment]
I've pushed v0.7.1 to Nuget, which I think should fix the problem you're having.
