### ISSUE TITLE
Bug when exporting SystemLandscapeView to PlantUML

### ISSUE THREAD

**Issue by haakoo** [structurizr/dotnet#36]
When running the `BigBankPcl` example through the `PlantUMLWriter` the `SystemLandscapeView` is exported with a bug.

As of commit: 7ec799e62b950e0d47bfb4e7a9f5add189245cf5

## Actual
Notice the line `package Big Bank plc {`
``` 
@startuml
title System Landscape for Big Bank plc
caption The system landscape diagram for Big Bank plc.
actor "Personal Banking Customer" <<Person>> as 1
package Big Bank plc {
...
}
...
@enduml
```

## Expected
Based on the other lines with `package` I expect it should have been `package BigBankPlc {`
``` 
@startuml
title System Landscape for Big Bank plc
caption The system landscape diagram for Big Bank plc.
actor "Personal Banking Customer" <<Person>> as 1
package BigBankPlc {
...
}
...
@enduml
```

**Comment by simonbrowndotje** [comment]
This has been fixed ... the PlantUML writer has also been moved to its own project, and will be pushed to Nuget in a few days.
