### ISSUE TITLE
How to set location of elements in a view? 

### ISSUE THREAD

**Issue by hopengfoong** [structurizr/dotnet#37]
Hi, 

I am trying to set the position of the elements in a diagram programmatically. 
Right now, what structurizr generates looks like this
`"elements": [
          {
            "id": "33"
          },
          {
            "id": "1"
          },
          {
            "id": "2"
          },
          {
            "id": "3"
          },
          {
            "id": "75"
          }
        ]`
If I upload the workspace to structurizr.com & use the editor to drag elements around the each object in the json has x and y property. 

My question is how do i set the position programmatically without going through the editor?

I've tried finding the ElementView in View.Elements & then setting the X and Y but it doesn't work. 

Thanks! :)

**Comment by simonbrowndotje** [comment]
You're right, you need to set the ```x``` and ```y``` properties of the ```ElementView``` instances on each view. You'll also need to set the ```mergeFromRemote``` property on your ```StructurizrClient``` instance to false to force your coordinates to take priority. A word of caution, if you do set this property to false, any changes you make to diagrams via the web UI will be overwritten each time you push a new version of the workspace using the StructurizrClient.

**Comment by hopengfoong** [comment]
Hi Simon,

Sorry for the late reply. I tried it just now and it worked! Thanks! :)
