### ISSUE TITLE
Null reference in GetWorkspace when downloaded workspace isn't encrypted

### ISSUE THREAD

**Issue by haraldgl** [structurizr/dotnet#38]
Hi,
I'm getting a null reference error in GetWorkspace when trying to upload a client side encrypted workspace.
The workspace is new and empty. 
In the Java version there is a check for encryption on the returned workspace - this check is missing in the .Net version. 
The result is that it is not possible to create an encrypted workspace.

**Comment by simonbrowndotje** [comment]
Thanks, I'll release a 0.8.3 version to nuget to fix this.
