### ISSUE TITLE
Could not load type 'Structurizr.Taggable' from assembly 'Structurizr.Core, Version=0.9.0.0

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [structurizr/dotnet#39]
Hi,

I am trying to create a small example of a Dgml using the most recent nuget packages and am getting:

Could not load type 'Structurizr.Taggable' from assembly 'Structurizr.Core, Version=0.9.0.0

When I call:
var dgml = workspace.ToDgml();

Code is:
			Workspace workspace = new Workspace("Getting Started", "This is a model of my software system.");
			Model model = workspace.Model;

			Person user = model.AddPerson("User", "A user of my software system.");
			SoftwareSystem softwareSystem = model.AddSoftwareSystem("Software System", "My software system.");
			user.Uses(softwareSystem, "Uses");

			ViewSet viewSet = workspace.Views;
			SystemContextView contextView = viewSet.CreateSystemContextView(softwareSystem, "SystemContext", "An example of a System Context diagram.");
			contextView.AddAllSoftwareSystems();
			contextView.AddAllPeople();

			Styles styles = viewSet.Configuration.Styles;
			styles.Add(new ElementStyle(Tags.SoftwareSystem) { Background = "#1168bd", Color = "#ffffff" });
			styles.Add(new ElementStyle(Tags.Person) { Background = "#08427b", Color = "#ffffff", Shape = Shape.Person });

			// Convert to DGML
			var dgml = workspace.ToDgml();
			// Write to file
			dgml.WriteToFile("example.dgml");

**Comment by simonbrowndotje** [comment]
The Taggable type has been renamed, so you'll either need to revert the Structurizr for .NET libraries back to v0.8.1 (I think), or raise an issue on the [Structurizr.Dgml](https://github.com/merijndejonge/Structurizr.Dgml) project.

**Comment by merijndejonge** [comment]
@simonbrowndotje What is the new name of Taggable? I'll update Structurizr.Dgml.

**Comment by simonbrowndotje** [comment]
It's now called [ModelItem](https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/Model/ModelItem.cs), and should hopefully just be a simple rename.

**Comment by merijndejonge** [comment]
Replacing Taggable by ModelItem seems to just work. Thanks. 
I've uploaded version 1.2.2 of Structurizr.Dgml to nuget.
