### ISSUE TITLE
WorkspaceUtils does not load containers' properties

### ISSUE THREAD

**Issue by robefernandez** [structurizr/dotnet#40]
After use the method LoadWorkspaceFromJson from the WorkspaceUtils, the containers from the loaded workspace don't contain the previous saved properties.

I've checked that all properties are in the JSON file but not in the objects after deserialization.

Regards.

**Comment by simonbrowndotje** [comment]
Any chance you could put a simple example together please, or provide more detail? The ```LoadWorkspaceFromJson()``` method is just a wrapper around the ```JsonReader``` class, so there may be a wider issue here with deserialisation. Thanks!

**Comment by robefernandez** [comment]
No problem Simon, here you have an example:
![image](https://user-images.githubusercontent.com/3029589/49797229-1876b580-fd3f-11e8-8b06-e53b72b38d04.png)


[StructurizrDotNetIssue40.zip](https://github.com/structurizr/dotnet/files/2667287/StructurizrDotNetIssue40.zip)

**Comment by simonbrowndotje** [comment]
Thanks again, this has been fixed and will be included in the next Nuget release later this week.
