### ISSUE TITLE
Interfaces as components and 'orphan implementation components'

### ISSUE THREAD

**Issue by robefernandez** [structurizr/dotnet#41]
Hi all!

I suppose that this 'issue' is affecting to many people but maybe they have found some workarounds or the API supports it but I haven't found how to do it.

Let me explain the case...

Inside my containers I have many components related to each other with no problem but sometimes those components are declared as interfaces. 
I'm using interfaces because they could be instanced by objects that implement the mentioned interface for different purposes and behaviors.

I haven't found how to make relationships programmatically between 'component interfaces' and the components that implement them.
The 'implementations components' appears on the chart as orphans components.

Is it possible? If not, could it be a new feature? 

I've attached a quick schema just to clarify it.

![image](https://user-images.githubusercontent.com/3029589/50337147-85910480-0510-11e9-99f4-1a34b6425743.png)

**Comment by robefernandez** [comment]
Am I the only one with this case? :sweat_smile:

**Comment by robefernandez** [comment]
Hi Simon, thanks for your reponse.
There's no problem declaring components as interfaces. The issue that I have is for the components that extends from the interfaces and they are used dynamically.
For example I declare a variable as an interface and it could be different components depending on each implementation of the interface. 
I don't know how to show in the diagram that the mentioned variable could have different implementations.
Regards.

**Comment by simonbrowndotje** [comment]
So you have multiple implementations of a component interface?

**Comment by robefernandez** [comment]
Yes, I do. 
If I use any hardware device for example, I have an interface to define the methods that I will use in my software but each device have their own SDK so I extend the interface to adapt each SDK to my software. And then I load each device using reflection.

**Comment by simonbrowndotje** [comment]
Creating your own annotations and a custom component finder strategy is certainly possible, and relatively straightforward. I'm still interested in your thoughts on how you would draw a component diagram (on a whiteboard) to represent this. Also, what tooling are you using to create the diagrams?
