### ISSUE TITLE
Are there any plans to extend `PlantUMLWriter` with support for C4-PlantUML?

### ISSUE THREAD

**Issue by binaryunary** [structurizr/dotnet#47]
The question is in the title. I'm just wondering whether this is something that's on your roadmap?

**Comment by simonbrowndotje** [comment]
It's not on the roadmap I'm afraid.

**Comment by coldacid** [comment]
https://gist.github.com/coldacid/465fa8f3a4cd3fdd7b640a65ad5b86f4

**Comment by jtreher** [comment]
@coldacid Were you using a different version of the client? It looks like the GetTags() method is missing on Structurizr.Relationship and Structurizr.Element.

**Comment by coldacid** [comment]
@jtreher No, `GetTags()` is just an extension method I forgot to include:

```
        public static IEnumerable<string> GetTags(this ModelItem element)
        {
            if (String.IsNullOrWhiteSpace(element.Tags))
                return Enumerable.Empty<string>();
            return element.Tags.Split(new [] { "," }, StringSplitOptions.RemoveEmptyEntries);
        }
```

**Comment by jtreher** [comment]
@coldacid Nice, thanks, bud.

**Comment by jtreher** [comment]
@coldacid Have you considered a PR for this? I've been using it for the past week and it's been pretty solid. I also added a bit to add a hyperlink on components which is useful for SVGs.

**Comment by jtreher** [comment]
@simonbrowndotje Would you be opposed to a pull request which merges in @coldacid's changes? The only issue right now is that the C4-PlantUML project might be abandoned. The current version is broken, but users have provided fixes which I have pulled down locally and modified. 

I also modified @coldacid's code to include a hyperlink container for when we are exporting SVGs so that you can provide links from one diagram to another. In addition, I've added an async relationship style.

**Comment by simonbrowndotje** [comment]
Feel free. :)

**Comment by jtreher** [comment]
@simonbrowndotje I'm not sure what the appropriate path is here though with the dependency on an external repository for generating the .PUML styles, especially if that particular project is now defunct. We could fork it and bring it into this one as one option.

Alternatively, maintaining a separate repository that overrides or extends your work with the coupling to the C4PlantUML repository is another option, however, any changes made here would then break those extensions.

**Comment by kirchsth** [comment]
In the added C4PlantUMLWriter I uses basically the PlantUML C4-stdlib, that it should work out of the box. Only the missing Dynamic.puml and Deploymnet.puml is explicit added to the diagrams, or can be used via  
```
!includeurl https://raw.githubusercontent.com/kirchsth/C4-PlantUML/master/C4_Deployment.puml 
```
(details see https://github.com/kirchsth/C4-PlantUML until the pull request is accepted)

A generated sample diagrams looks like 
![Deployment diagram for Internet Banking System - Live](http://www.plantuml.com/plantuml/png/pLTjJniv4FwUNp6NBuKA27aX8LLL5G9jgNX1RBZUdKvQpNfd4mkllRAzfFJK_txZsut2zbvesbGw919xPkndPfwnntdjF5fVvghrazH2bIcLLi7S-yAzw7GiBlPcqi_Bf7HaXT6UjDyJ9k_SIIlcpiyxay7kjKBjRo_EEpawJvP5yGaLoZpamRe8cp-3KlEo800_9yYCKcOXzGoKr0IeKsYefNKyCi2me8n0fHvuZwMBy78oQAAyQh5wwGUaXXneuy6LHM6i1oozoT5BKS4bbl3EWSaWX8GiiZiWCw3OavXha0xkoJumCZieDOVk6miNd19WmFRBZfEVwDNl-cNuVZ4zdRoxZDzSNKxZwEotqrTjjd6O5ueSEEBbn46tMbvwHN2cFLbD7evHtuLCH0_EKmwxi0ghrJe_-lNgTXf_E9k-YyzFtvvUdcnjjrehY_ZIfBJrQ1wVotkAusCv2_iMIiHnFpliPabl1zeiXI06bhU_c4EA7a5GSAkz3N-q0DQ3IUGiuV62akVFdyTnhv_j4mf6gHMxbGQsFWws0_XjKcfVGdUujp-0ysbKWtudx561OavJamjaSnmCHWF6ggHGYTjV2k1mx-CIdVycow8uqywZ5hIrvAgcgc8gZZzGSbGKIl8MqkWUnpmOzzDqpFkp2Xxf0kHxlCTGwH0LDl1zyVCaY4z8SKpMXS87nWjLMf-qO1t4grf9wbfn_A482fmHu0fchxqTOe3FBVx_LWAna1M10n87muD715OQ9l1mumIkO9i4zW_7MNyy_c4K7bsVDIdi9gD-sYFUdrLVIU6rDVSo9VTtdh9IYx0ObVGFS2yH4Dv7LvUTTzFfTGGCiH7AqcI_owuBCSuE7XCMv9jdgaAxiYWKNLkPettWQZdCHkDio62L0dQXrhLNicvF_1T99yc_qNI27XDq50ZAUhrH5WxrKXW0RaXXbMXOYY4ISyenQ2DlB3a8JGmipQJp5eCrI9qPcsCOxy0StPpIq2pcf7rDEmXBQPYYSZk0Gf1peCoC9-J5fjWBTmSX7Go7JVPwFuIztfAzY8JHQSNV8EtsKthCNwNTC8DzFjEzyL3WyF_8uEUlQAsJqdcJattcXCcBqfFbx8d-CA6K7LrfOQaE_bz8OOqpcOSFKgTcuS1O2BSBmHEFY1p5rPBoRtEEUz6nPSWmxXxszqVPgEvGjJWu-DQOq54cSylBT-32V99AuLFElP6MClDnfmubmWoj16EVMhTAnsaweogwTQxjYCUAhd56NpJWdX33NiBnL1QxmUIVRl58M5bK3VP8pqg5jd6Her9Wij1xdxhJlG5Hvzo52pwiaHOMb41IPJTKsFgrbPj4AahfNWeARH3tH_j9ixug4wXiWliL2V8gWb1SEhL6fbLklpwp5s7JaDNGK99at1qBthcI0ei3pY-OCyswcJ5GCfUUKd1buiX_N_eQeN42ENatfDPlukkqanl2r45cJGwXB1PMUdBWpLybSt8yOIysxaFZGbp3XpMuM__XSu5t3Ce6852f9VpgsT9qOksZ-QCSYc-BzH_gtnP4uzbk8DIvM9tBHsU_zkoSCh-9jzLc6lmDLI6HgtxpUSDklYQTbhdw4m00 "Deployment diagram for Internet Banking System - Live")
