### ISSUE TITLE
Adding or changing the URL for an Icon in an ElementStyle resets the positions of all elements when uploaded

### ISSUE THREAD

**Issue by jacquibo** [structurizr/dotnet#51]
I have updated to version 0.9.1 and added icons to three of my ElementStyles. Each time I add or make a change to the Icon on one of these ElementStyles, then upload the workspace, the positions of all elements in all diagrams are reset, and all appear in the top left corner.

This is unusable as it means redesigning every diagram every time a new icon change is made.

Please tell me if there is a setting/fix/workaround for this.

**Comment by simonbrowndotje** [comment]
Apologies, there was a bug in 0.9.1 ... a new version (0.9.2) is currently being published on nuget. I would recommend importing the version of your workspace where the element positioning was okay, and then upgrading your client to 0.9.2, everything should work as expected.

You have a couple of options to get previous versions of your workspace: (1) the client library retains all versions of the JSON workspace files in the working directory; or (2) you can activate your Structurizr trial (using the link on your dashboard), and you'll be able to load the previous version of your workspace, and then export it to a file using the "Export" button on the workspace summary page.

You can use the "Import" button on your workspace summary page to import a specific JSON file.

**Comment by jacquibo** [comment]
Brilliant, that solved my issue :)
Useful to know about the json files being saved. My files are also in a git repo, to add extra version control.
