### ISSUE TITLE
How to change Component's/Container's Name

### ISSUE THREAD

**Issue by alexey-aurea** [structurizr/dotnet#53]
Hi,

Is it possible to change Component's or Container's name without re-creating it ? I see that the Name property has internal set and I could not find an easy way to change the name. Do you have any recommendation about it ?

**Comment by simonbrowndotje** [comment]
What are you trying to achieve by changing the name of an element?

**Comment by alexey-aurea** [comment]
I am trying to achieve the change of the element's name ..

**Comment by simonbrowndotje** [comment]
The software architecture model is designed to be immutable when created with the C# client library. So, if you're using the C# client library, you can change the name of an element by changing the code that creates the software architecture model. And if you're using the component finder and are not happy with the names it's setting, you can create your own component finder strategies to change this behaviour. Does that help?

**Comment by alexey-aurea** [comment]
Not really,

I am using C# api to create a workspace out of a simple yaml file. But your C# api libraries do not allow renaming (if this renaming happens on the yaml file).
I have given you multiple scenarios on when this could happen. I am NOT using C# diagram from code generator, so your suggestion does not help.

**Comment by simonbrowndotje** [comment]
I'm not sure that I understand how you're using the C# library then I'm afraid. You have a YAML file that contains a model of your software architecture? And you're using the C# client library to parse this YAML file, and create a Structurizr software architecture model? If so, why not modify the names of elements in the YAML file? Can you share an example?

**Comment by alexey-aurea** [comment]
Yea, excellent! You got it, there is somewhere a descriptor of the model (could be a yaml file or whatever) and there is also an existing Structurizr model+diagrams.
I need to examine the differences and adjust Structurizr model and views is need be.
So here is the problem I cannot update element's name using C# libraries as you made it internal :-)

**Comment by simonbrowndotje** [comment]
The name property is internal and can't be changed after being set so that some rules in the model can be enforced (e.g. names are unique within their parent context). For this reason, I'd recommend modifying the element names during the YAML import process, rather than trying to change the names of existing model elements after the YAML has been imported.

**Comment by alexey-aurea** [comment]
Ok, so I have a structurizr Model already. And I am loading the file in memory. I see that an exisitng element in Structurizr's model is different to the yaml, so I need to rename it (keeping other properties intact like relationships and so on)
How would I do that ?
Also, why didn't you simply add a method like Rename or SetName or whatever to the element. Since it has access to parent it can traverse all the tree to ensure the name is unique..
Also, why must it be unique if you have a unique element's ID ?

**Comment by simonbrowndotje** [comment]
Changing the name of elements is on the todo list, but it's not implemented yet I'm afraid ... I will look at doing this later in the week. The uniqueness is related to not having two elements with the same name on a diagram, because that would cause confusion.

**Comment by alexey-aurea** [comment]
You do not know for sure. If you rely on element's name being unique then why do you need a unique Id ?
Also, in my case we need components with the same name in the model but they will belong to different containers. Which actually would make it hard to aggregate them on the same diagram.

**Comment by simonbrowndotje** [comment]
Within a workspace, all of the internal references to elements (e.g. relationship source and destination, elements included in a view, etc) are done by the internal ID. As I said above, elements need to be uniquely named within their parent context ... so you can definitely have two components with the same name, provided they are defined in different containers.

**Comment by alexey-aurea** [comment]
One more question, why is it that Container has menthod AddComponent but does not have a method RemoveComponent ?
What if I want to remove a component which other component references ?

**Comment by simonbrowndotje** [comment]
The original design intent of the client library was that people would write a C# program to build a workspace, and then upload that workspace to the Structurizr service. If something in the workspace needed to be changed, they would change the C# code and rerun the program.

In essence, the client library was designed to be append-only, and not manipulate an existing model. This is why it's currently not possible to change element names, remove elements, etc.

**Comment by alexey-aurea** [comment]
But it is possible to do all these things using json and then simply upload it.. Why so many limitations on the client SDK when this is actually not restricted via the API itself ?
I am using your SDK to parse json and alter existing model. but looks like i have to write my own parser and API interactions implementation to get past of your idea of 'append only', right ?

**Comment by simonbrowndotje** [comment]
Yes, all of this is possible with the JSON, and in fact the browser-based workspace editor does allow users to manipulate the workspace (via the UI). As I said, the original design intent of the client library was to be append-only.

**Comment by alexey-aurea** [comment]
I understand what you are saying it just does not make sense. As if instead of implementing a 1 to 1 sdk for your API someone just decided to cut some slack.. 
Anyway, I am going to fork your repo to re-use some code for our needs. Thank you for all the help.

**Comment by alexey-aurea** [comment]
Also, for some reason when a file gets uploaded to the web there is no enforcement on unique IDs.. just FYI.
Same file cannot be parsed by your sdk.
