### ISSUE TITLE
Views aren't positioning anything

### ISSUE THREAD

**Issue by LynxStar** [structurizr/dotnet#56]
Hopefully this is just me misunderstanding the documentation but using BigBankPlc.cs for example produces a diagram that looks like 
![image](https://user-images.githubusercontent.com/1655924/69905728-d1d1ff00-1385-11ea-84ae-de2b90dea399.png)

I cannot find any documentation on how to automatically position them (which both the documentation and the example has no code about positioning them) or how I would even manually do this.

The X/Y position isn't exposed when you add the components and if you retrieve the Elements you get a copy so you can't directly set the X/Y position.

Can someone point me in the correct direction to produce an identical diagram to the ones in the example documentation?

**Comment by simonbrowndotje** [comment]
I've updated the [getting started guide](https://github.com/structurizr/dotnet/blob/master/docs/getting-started.md) ... Structurizr doesn't provide any auto-layouting by default, so you need to open the diagram in the online diagram editor, move the boxes around, and then save the workspace. The API client will attempt to retain the diagraming layout information during subsequent uploads of the same workspace.

**Comment by LynxStar** [comment]
Makes total sense. I am able to see this functioning as intended thanks to that information. I can see via the `MergeFromRemote` how it downloads what's currently there and pulls over the styling and position information that is applicable.

I'll mark this as closed.
