### ISSUE TITLE
AutoLayout

### ISSUE THREAD

**Issue by VikingExplorer** [structurizr/dotnet#57]
Whenever I run my .net core app to update the model, all my diagrams revert to being all bunched up.  I have to edit the diagram and click on "AutoLayout".   I've looked, but I can't find the method to call to do perform an auto-layout function.

**Comment by simonbrowndotje** [comment]
Are you clicking the "Save workspace" button after running the auto-layout function?

**Comment by VikingExplorer** [comment]
Yes, but to clarify, I'm looking for a way to not have to use the web UI to touch the diagrams.  

I'm expecting to run my C# code, and for the diagrams to maintain their auto layout-ness.

What's happening is that everything I run the code, all the elements lose their location, and bunch up on top of each other.

I have to go in, reapply AutoLayout, Save & exit.

So, is their a method I can call from the C# code to auto-layout after changes?

**Comment by simonbrowndotje** [comment]
This has been supported by the Java client library for a while, but not the .NET version, so I've just ported it -> https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/View/View.cs#L294

I'll push this to nuget in the next couple of days.

**Comment by simonbrowndotje** [comment]
0.9.4 is now on nuget.

**Comment by VikingExplorer** [comment]
Now that's what I call great, responsive service!
