### ISSUE TITLE
Nested Software systems?

### ISSUE THREAD

**Issue by VikingExplorer** [structurizr/dotnet#58]
Can Software Systems be nested?    What is the "Relationship" functionality intended for?

**Comment by simonbrowndotje** [comment]
> Can Software Systems be nested?

No

> What is the "Relationship" functionality intended for?

I'm not sure what you're asking.

**Comment by VikingExplorer** [comment]
On the 2nd question, was curious about this code:

model.Relationships.Where(r=>r.Destination.Equals(secondaryDatabase)).ToList().ForEach(r=>r.AddTags(FailoverTag));
                Relationship dataReplicationRelationship = primaryDatabaseServer.Uses(secondaryDatabaseServer, "Replicates data to", "");
                secondaryDatabase.AddTags(FailoverTag);

The text of **FailoverTag** doesn't seem to appear anywhere. It appears to grey out the shape?

AND

            rdms.AddTags(ExistingSystemTag);

The shape turned gray, apparently indicating that it's an existing system.

Question: Are these strings controlling the behavior?  If so, why aren't they enums?

**Comment by simonbrowndotje** [comment]
This might help -> https://github.com/structurizr/dotnet/blob/master/docs/styling-elements.md

(in essence, every element and relationship can have a free-text tag, and styles can be associated with these tags)
