### ISSUE TITLE
Does not support UWP projects

### ISSUE THREAD

**Issue by edgarssults** [structurizr/dotnet#6]
The current version of Structurizr package cannot be added to UWP projects:

Package Structurizr.Core 0.4.0.1 is not compatible with uap10.0 (UAP,Version=v10.0). Package Structurizr.Core 0.4.0.1 supports: net40 (.NETFramework,Version=v4.0)

**Comment by simonbrowndotje** [comment]
Although not available on nuget yet, the Structurizr.Core library has been refactored to now run on .NET Standard 1.3, which should let you use it with UWP projects.
