### ISSUE TITLE
Structurizr.PlantUML uses "Software System" as tag although I added one myself.

### ISSUE THREAD

**Issue by niem94** [structurizr/dotnet#60]
Code that adds a tag, fx "Intermediary"
<img width="813" alt="image" src="https://user-images.githubusercontent.com/26203420/73649180-825ac880-467f-11ea-925b-5ffeb6a18133.png">

Resulting plantUML Diagram:
![image](https://user-images.githubusercontent.com/26203420/73649424-0b71ff80-4680-11ea-8649-a9322d5d9140.png)

Expected result:
I expect the Added Tag to be used in the PlantUML Diagram, so It does not write "Software System", but fx. "Intermediary".

**Comment by simonbrowndotje** [comment]
PlantUML support has moved to the dotnet-extensions repo, so please feel free to open an issue there instead -> https://github.com/structurizr/dotnet-extensions/issues

Thanks!

**Comment by niem94** [comment]
My bad, ill move it there. Thanks for the quick response.

**Comment by simonbrowndotje** [comment]
You can use the [Terminology](https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/View/Terminology.cs) class (workspace.Model.Views.Configuration.Terminology) to customise the terminology used when rendering the diagrams, but this applies to all diagrams within a workspace.
