### ISSUE TITLE
Structurizr JsonWriter produces a file different from the one downloaded from the one downloaded from the https://structurizr.com/

### ISSUE THREAD

**Issue by alexey-aurea** [structurizr/dotnet#62]
The json file downloaded from the web seems to have more information than the one which could be obtained using the API.
Can this issue be fixed please and either or of those sources changed to match the other ?

**Comment by simonbrowndotje** [comment]
When you say "more information" ... what's missing?

**Comment by alexey-aurea** [comment]
Feel free to run debug on https://structurizr.com/share/47754

if you compare 2 json files, there are following sections missing from the API one:
Workspace is missing description
    
The following sections a missing from the web json:
Workspace is missing "lastModifiedUser", "lastModifiedAgent", "configuration"

And with the deep compare we got
Expected pair[model][people] to be a collection with 3 item(s), but {{[id, 2], [tags, Element,Person], [name, Product User], [description, A product developer], [relationships, System.Collections.Generic.List`1[System.Object]], [location, Unspecified]}, {[id, 1], [tags, Element,Person], [name, Test Developer], [description, A user who creates automated tests], [relationships, System.Collections.Generic.List`1[System.Object]], [location, Unspecified]}}"
    "contains 1 item(s) less than"
    "{{[location, Unspecified], [name, Administrator], [description, Views power consumption and power saving rates, and also manages PCs and Macs], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 3], [tags, Element,Person], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[location, External], [name, End user], [description, End user can wake up their computer remotely], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 50], [tags, Element,Person], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[location, External], [name, License Provider], [description, Provides new licenses or updates.], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 408], [tags, Element,Person], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}}.
    Expected pair[model][softwareSystems] to be a collection with 3 item(s), but {{[id, 3], [tags, Element,Software System,External], [name, CICD System], [description, External CICD system (TeamCity, Jenkins etc], [relationships, System.Collections.Generic.List`1[System.Object]], [location, Unspecified]}, {[id, 6], [tags, Element,Software System,External], [name, Jira], [description, Central Jira instances], [location, Unspecified]}, {[id, 7], [tags, Element,Software System,Internal], [name, Testing Services], [description, Testing Services instance], [relationships, System.Collections.Generic.List`1[System.Object]], [location, Unspecified], [containers, System.Collections.Generic.List`1[System.Object]]}, {[id, 5], [tags, Element,Software System,External], [name, Testrail], [description, Central Testrail instance], [location, Unspecified]}}"
    "contains 1 item(s) more than"
    "{{[location, External], [containers, System.Collections.Generic.List`1[System.Object]], [name, System Center Configuration Manager], [description, Microsoft SCCM features remote control, patch management, operating system deployment, network protection and other various services.], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 4], [tags, Element,Software System], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[location, External], [containers, System.Collections.Generic.List`1[System.Object]], [name, Domain Controller], [description, Domain controller manages user accounts, file server, print server, name resolution, etc], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 9], [tags, Element,Software System], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[containers, System.Collections.Generic.List`1[System.Object]], [name, Verdiem Power Management System], [description, Allows users to view power consumption and power saving rates, and also to manage PCs and Macs in the organization], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 1], [tags, Element,Software System], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}}.
    Expected pair[model][deploymentNodes] to be a collection with 11 item(s), but {{[id, 150], [tags, Element,Deployment Node], [name, Testing Services File Storage], [description, Testing Services File Storage], [environment, Default], [technology, AWS S3], [instances, 1], [containerInstances, System.Collections.Generic.List`1[System.Object]], [children, System.Collections.Generic.List`1[System.Object]]}, {[id, 137], [tags, Element,Deployment Node], [name, Testing Services Routers and Tasks], [description, Testing Services Routers and Tasks], [environment, Default], [technology, AWS Lambdas + API Gateway], [instances, 1], [containerInstances, System.Collections.Generic.List`1[System.Object]], [children, System.Collections.Generic.List`1[System.Object]]}, {[id, 141], [tags, Element,Deployment Node], [name, Testing Services VMs], [description, Testing Services VMs], [environment, Default], [technology, AWS EC2 Spot instances], [instances, 1], [containerInstances, System.Collections.Generic.List`1[System.Object]], [children, System.Collections.Generic.List`1[System.Object]]}, {[id, 159], [tags, Element,Deployment Node], [name, Testing Services Web Hosting], [description, Testing Services Web Hosting], [environment, Default], [technology, AWS S3 + CloudFront], [instances, 1], [containerInstances, System.Collections.Generic.List`1[System.Object]], [children, System.Collections.Generic.List`1[System.Object]]}}"
    "contains 7 item(s) less than"
    "{{[technology, Windows 7, Windows 10], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, Production], [name, Windows Client], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 233], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, Mac OS X], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, Production], [name, Mac Client], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 234], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, VMWare, Windows 10], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, QA], [name, Windows Client], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 198], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, Windows Server 2016+, MS SQL 2008+], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, Production], [name, Database Server], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 232], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, Mac Stadium], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, QA], [name, Mac Client], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 197], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, VMWare, Windows Server 2016], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, QA], [name, Application Server], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 195], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, Linux], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, QA], [name, License Server], [description, Hosts the python/django license server application], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 477], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, Windows Server 2016+], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, Production], [name, Application Server], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 231], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, Linux], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, Production], [name, License Server], [description, Hosts the python/django license server application], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 481], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, Windows Server 2016], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, Production], [name, SCCM], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 262], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}, {[technology, VMWare, Windows Server 2016], [instances, 1], [children, System.Collections.Generic.List`1[System.Object]], [containerInstances, System.Collections.Generic.List`1[System.Object]], [environment, QA], [name, SCCM], [relationships, System.Collections.Generic.List`1[System.Object]], [id, 196], [tags, Element,Deployment Node], [properties, System.Dynamic.ExpandoObject], [perspectives, System.Collections.Generic.List`1[System.Object]]}}.
    Expected pair[views][systemContextViews][0] to be a dictionary with 7 item(s), but has additional key(s) {"description"}
    Expected pair[views][containerViews][0] to be a dictionary with 6 item(s), but has additional key(s) {"description"}
    Expected pair[views][componentViews] to be a collection with 7 item(s), but {{[description, Development VMs Component Diagram], [key, DevelopmentVMsComponentView], [paperSize, A4_Landscape], [containerId, 124], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]], [animations, System.Collections.Generic.List`1[System.Object]]}, {[description, Test Services Component Diagram], [key, TestServicesComponentView], [paperSize, A4_Portrait], [containerId, 13], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]], [animations, System.Collections.Generic.List`1[System.Object]]}, {[description, Build VMs Component Diagram], [key, BuildVMsComponentView], [paperSize, A5_Landscape], [containerId, 88], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]], [animations, System.Collections.Generic.List`1[System.Object]]}, {[description, Provisioning Services Component Diagram], [key, ProvisioningServicesComponentView], [paperSize, A4_Portrait], [containerId, 33], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]], [animations, System.Collections.Generic.List`1[System.Object]]}, {[description, Test VMs Component Diagram], [key, TestVMsComponentView], [paperSize, A4_Portrait], [containerId, 104], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]], [animations, System.Collections.Generic.List`1[System.Object]]}, {[description, TS Portal Component Diagram], [key, TSPortalComponentView], [paperSize, Slide_4_3], [containerId, 46], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]], [animations, System.Collections.Generic.List`1[System.Object]]}}"
    "contains 1 item(s) less than"
    "{{[containerId, 392], [animations, System.Collections.Generic.List`1[System.Object]], [key, LicenseDatabaseComponent], [softwareSystemId, 1], [paperSize, A6_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}, {[containerId, 28], [animations, System.Collections.Generic.List`1[System.Object]], [key, MacClientAgentComponent], [softwareSystemId, 1], [paperSize, A5_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}, {[containerId, 23], [animations, System.Collections.Generic.List`1[System.Object]], [key, QueueServiceComponent], [softwareSystemId, 1], [paperSize, A5_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}, {[containerId, 15], [animations, System.Collections.Generic.List`1[System.Object]], [key, SurveyorDatabaseComponent], [softwareSystemId, 1], [paperSize, A6_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}, {[containerId, 391], [animations, System.Collections.Generic.List`1[System.Object]], [key, LicenseServerComponent], [softwareSystemId, 1], [paperSize, A5_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}, {[containerId, 27], [animations, System.Collections.Generic.List`1[System.Object]], [key, WindowsClientAgentComponent], [softwareSystemId, 1], [paperSize, A5_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}, {[containerId, 385], [animations, System.Collections.Generic.List`1[System.Object]], [key, VerdiemServerComponent], [softwareSystemId, 1], [paperSize, A4_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}}.
    Expected pair[views][deploymentViews] to be a collection with 2 item(s), but {{[description, Testing Services Deployment Diagram], [key, TSDeploymentView], [paperSize, A3_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]], [environment, Default]}}"
    "contains 1 item(s) less than"
    "{{[environment, QA], [key, VerdiemQADeployment], [paperSize, A5_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}, {[environment, Production], [key, VerdiemProductionDeployment], [paperSize, A5_Landscape], [elements, System.Collections.Generic.List`1[System.Object]], [relationships, System.Collections.Generic.List`1[System.Object]]}}.
    Expected pair[views][configuration] to be a dictionary with 5 item(s), but it misses key(s) {"viewSortOrder"}
    Expected pair[id] to be 48532L, but found 47754L.
    Expected pair[name] to be 
    "Avolin - Verdiem Enterprise Workspace" with a length of 37, but 
    "Testing Services Workspace" has a length of 26, differs near "Tes" (index 0).
    Expected pair[lastModifiedDate] to be <2020-01-27 18:06:56>, but found <2020-02-17 07:34:59>.
    Expected pair[revision] to be 298L, but found 319L.

**Comment by simonbrowndotje** [comment]
The following seems to suggest that you're comparing the JSON documents for two different workspaces, which is why you're seeing so many deep comparison differences:

```
Expected pair[id] to be 48532L, but found 47754L.
```

That aside, there will be some minor differences in the JSON created by the Structurizr .NET library vs that returned via the web API. The reasons for this include:

- The web API is written using Java, and uses the Structurizr for Java client library for JSON serialisation. Since there are no guarantees on element ordering in JSON, both libraries might do ordering slightly differently.
 - The Structurizr cloud service will modify some of the workspace metadata (e.g. last modified date/agent/user), so you'll see that being different too.

If you compare the JSON document created by the Structurizr .NET library with the version returned by the web API, for the same workspace, the JSON documents should mostly be semantically the same.

**Comment by alexey-aurea** [comment]
Yes, sorry, you are correct. I have updated the report. Our main concern is 'locations' and 'environment' are missing from API json. Any way to fix that ?

**Comment by simonbrowndotje** [comment]
Let me know which objects these properties belong to, and I'll take a look.

**Comment by alexey-aurea** [comment]
environment>> workspace.views.deploymentViews.item
location >> model.softwareSystems.item

**Comment by simonbrowndotje** [comment]
Both properties will now be outputted when the default/empty values are set.

**Comment by alexey-aurea** [comment]
Thanks!

**Comment by alexey-aurea** [comment]
Could you please also add an integration test to make sure such deviations won't happen in the future ?
