### ISSUE TITLE
Question: Is it possible to render a local workspace model, and not saving it to my cloud workspace?

### ISSUE THREAD

**Issue by niem94** [structurizr/dotnet#65]
Hi, I just aqquired a Structurizr cloud license, but I have some problems in making the implementation that fullfill my requirements. 

So first off, I am making a website that relies on Structurizr to render and show business models (a markets stakeholders and their relationships) on my site primarily through the provided iframe and image render functionality. This is used for educational and business uses. At first i used the PlantUML extension, which worked well, but it sadly was way to static, and did not allow the representation that I need. I now moved to a cloud plan to use the Structurizr rendered C4 model, which is perfect for my needs. 

Problem is I only need to render these models with Structurizr, but I am not interested in saving the data to a workspace for the following reason:

> I need an unlimited amount of workspaces in that case, as each and every user should be able to create whatever amount of business models on the site (a business model == a workspace.Model in my situation).

So my question is if it is possible to render a local workspace model with the Structurizr C4 Model, without needing to push it to my cloud workspace. If so how, and are there any disadvantages? As the only other solution I see is to use my workspace as a temporary "server" to render a pushed model. This would most certainly give me problems with multiple concurrent users, and it is inherently a very hacky solution I don't like.

**Comment by simonbrowndotje** [comment]
Unfortunately not ... the Structurizr cloud service is designed to locally render (i.e. in the web browser) content that is stored on the cloud service. Your best approach might be to not use the Structurizr cloud service, and create your own rendering engine instead.

**Comment by niem94** [comment]
Hmm, I was afraid you'd said that :-) You don't plan to provide any service/plan that allows temporary rendered models (kinda like plantumls web service) in the future? That would allow Structurizr to fit a lot of use cases which are not possible with the limited amount of workspaces.

**Comment by simonbrowndotje** [comment]
Nothing planned I'm afraid ... Structurizr uses client-side rendering, whereas PlantUML can render on the server. You might want to take a look at the FC4 project, because they are possibly building their own rendering engine -> https://github.com/FundingCircle/fc4-framework/issues/5

**Comment by niem94** [comment]
Thats a bummer, do tell if that changes .. :-) Ill use the cloud plan for now, to preview the c4 model with the program some more. And then I'll look into fc4 and other tools for future iterations.
