### ISSUE TITLE
Support so omnidirectional relationships are not placed on top of each other

### ISSUE THREAD

**Issue by niem94** [structurizr/dotnet#67]
Hi, right now there is no way to avoid omnidirectional relationships stacking on top of each with automatic layout. This is how it looks:

![image](https://user-images.githubusercontent.com/26203420/77347135-acec0800-6d37-11ea-8abb-2a5dcf32a7bf.png)

**Comment by simonbrowndotje** [comment]
Setting the [vertices](https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/View/AutomaticLayout.cs#L77) property to true should help with this, but it will affect all vertices on the diagram.

**Comment by niem94** [comment]
@simonbrowndotje THANK YOU! I don't mind it being a little jaggy :-)

![image](https://user-images.githubusercontent.com/26203420/77354750-9fd51600-6d43-11ea-8a85-559e83017e0d.png)
