### ISSUE TITLE
Question: Is it possible to download a diagram as an svg/png through the web api?

### ISSUE THREAD

**Issue by niem94** [structurizr/dotnet#68]
I remember having asked this before, but I haven't been able to find the issue with the answer, so sorry for the inconvenience!

As the embedded iframe do not have the export button, I need another way to export the diagram as is, but without taking the user off site. Is this possible with the web api?

**Comment by simonbrowndotje** [comment]
Unfortunately not, because the diagrams are rendered client-side. You could potentially use the [Scripting API via Puppeteer](https://github.com/structurizr/puppeteer) though.

**Comment by niem94** [comment]
I made it work, by using a hyperlink with the download property.
```html
<a url="https://structurizr.com/share/{workspaceId}/{diagramId}/images/{imageName}.png" download/>
```
This does not prompt for a download, as that is not supported by browsers ([see this](https://stackoverflow.com/a/49736875/10171898)), but it does open the image in a new tab, so the rest is just to right click and save as image. 

Thanks for sharing Puppeteer, I'll try to fiddle some with it to see if that makes for a better solution :-)

**Comment by simonbrowndotje** [comment]
In addition to making your workspace accessible without authentication (```/share``` in the URL suggests that you've made the workspace public, which may be okay for your use case, but I'd generally advise caution doing this), you may find the image URL doesn't work as expected. The [images behind those static URLs are not regenerated immediately](https://structurizr.com/help/embed-image) when a workspace has been modified, so you will very likely see an older version at times. We've added the PNG export button to the embedded iframe.

That said, to answer the question of the issue title, "Is it possible to download a diagram as an svg/png through the web api?":

1. No. The JSON based web API, and by extension the .NET client library, does not have the ability to download PNG versions of the diagrams.
2. If you want to download the current diagram(s) as PNG files, via the command line, you'll need to use Puppeteer to start up a web browser in headless mode.

**Comment by niem94** [comment]
Thanks, I did notice the images were not available at all times, and came to the same conclusion with regard to security issues. 

Nice to hear you've added an export button. That solves my use case even better 👍
