### ISSUE TITLE
problem loading workspace in Structurizr

### ISSUE THREAD

**Issue by ketevan-b** [structurizr/dotnet#73]
HI
 have problem loading workspace in Structurizr ,
When I do the upload model, to specific workspace, let’s say Workspace ID: 3

I get following error window
![image](https://user-images.githubusercontent.com/61318524/94690932-c18e0600-0341-11eb-9782-cd90e1482e60.png)

Performing upload to alternate workspace (Id: 2), comletes sucessfully

Could you help me?
Thanks in advance !

**Comment by ketevan-b** [comment]
Full stack trace is
 at Structurizr.Api.StructurizrClient.PutWorkspace(Int64 workspaceId, Workspace workspace)
 at C4.LibertyBank.Program.Main(String[] args) in C:\Users\ketevan.burjanadze\source\repos\C4\C4.LibertyBank\Program.cs:line 24

**Comment by simonbrowndotje** [comment]
Are you running the latest version of the on-premises installation, and the .NET client library?

Is there more to the stack trace? (you should see the `JsonReaderException` somewhere in the stack trace)

**Comment by ketevan-b** [comment]
Full stack trace is
 at Structurizr.Api.StructurizrClient.PutWorkspace(Int64 workspaceId, Workspace workspace)
 at C4.LibertyBank.Program.Main(String[] args) in C:\Users\ketevan.burjanadze\source\repos\C4\C4.LibertyBank\Program.cs:line 24

**Comment by simonbrowndotje** [comment]
There should also be an "inner exception" somewhere, with more information ... which you should be able to find by clicking "View details" or "Exception settings" on the popup window.

**Comment by ketevan-b** [comment]
I have 
 structurizr  build 1778 version

**Comment by ketevan-b** [comment]
![image](https://user-images.githubusercontent.com/61318524/94696270-e9806800-0347-11eb-9bb0-6701b0f70671.png)

**Comment by simonbrowndotje** [comment]
I would try upgrading everything to see if that resolves the problem. If not, and you're able to, feel free to send us the `DATA_DIRECTORY/3/workspace.json` file to `help@structurizr.com` and we'll take a closer look.

**Comment by ketevan-b** [comment]
I have already requested a version update as soon as I receive the updated version I will check and notify you of the result
thank you

**Comment by ketevan-b** [comment]
Hi 
I updated the versions, but this did not help my problem, just as I later realized that due to the size of the project, the workspace was not being updated  and I  solved this  task.
But with the update of structurizr  version another problem appeared on deployment diagram no visible deployment node 
for example
![image](https://user-images.githubusercontent.com/61318524/95326867-4b931d00-08b4-11eb-9b57-a52f8852ef74.png)
when  used dark mode it is visible
![image](https://user-images.githubusercontent.com/61318524/95327014-809f6f80-08b4-11eb-8180-1f41449954fe.png)

**Comment by simonbrowndotje** [comment]
To resolve the deployment node text issue, you can either:

1. Add an element style for the `Deployment Node` tag, with the `color` property set.
2. Find where you have an element style with a white `color` property, and remove or move this.

**Comment by ketevan-b** [comment]
Tank you I do it
