### ISSUE TITLE
Add support for changing the Container tag string

### ISSUE THREAD

**Issue by pipeworks-zz** [structurizr/dotnet#74]
I'd like to change the Container tag from "Container" to "Process" to avoid confusion with Docker containers.

Would it be possible to add support for this? or any guidance on how to go about it if i'd like to do it myself?

**Comment by simonbrowndotje** [comment]
If you're using the Structurizr rendered, you can [change the terminology](https://structurizr.com/help/terminology) via the [Terminology](https://github.com/structurizr/dotnet/blob/master/Structurizr.Core/View/Terminology.cs) class (available via Workspace.Views.Configuration).

**Comment by pipeworks-zz** [comment]
Perfect. Thanks!
