### ISSUE TITLE
HttpClient shouldn't be disposed all the time

### ISSUE THREAD

**Issue by MirzaMerdovic** [structurizr/dotnet#75]
Hi,

Thanks for the great software and extra thanks for providing .net client libraries. I have been looking through the code and I noticed that HttpClient gets disposed every time a call is made to either: Get, Put. Lock or Unlock Workspace methods. Is there a reason for this decision, or it's just an oversight?
 
HttpClient should not be disposed on each call since that can lead to [port exhaustion issues](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/). 
Preferred way would be using [IHttpClientFactory](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests), but having a static instance can also work in lots of scenarios and I would say in the case of Structurizr as well.

I would be wiling to contribute with a PR to fix this if you consider it an issue that should be fixed.

Kind regards,
Mirza

**Comment by simonbrowndotje** [comment]
Thanks for raising this, it's just an oversight. I don't imagine this library is used in any long-lived .NET processes, so it's probably not going to impact anybody. But you're welcome to submit a PR if you want to.

**Comment by MirzaMerdovic** [comment]
@simonbrowndotje PR submitted.

**Comment by MirzaMerdovic** [comment]
Based on our discussion in my PR, I will close this one.
