### ISSUE TITLE
SoftwareSystemInstance support

### ISSUE THREAD

**Issue by sdiachen-ss** [structurizr/dotnet#77]
Hi all,
First of all thanks for the work you've put into this project.

Do you have any plans for SoftwareSystemInstance support in .NET?
AFAIK it is supported in DSL and Java.

Regards,
Sergii

**Comment by simonbrowndotje** [comment]
Thanks, yes, it's on the todo list (I think I have a partial implementation that just needs finishing off).

**Comment by simonbrowndotje** [comment]
All of the code to support software system instances is now in this repo ... feel free to build from source and try it out. I'll push a new release to Nuget in the next week or so.

**Comment by simonbrowndotje** [comment]
v1.0.0 is now on Nuget.
