### ISSUE TITLE
Updating diagram without running the code

### ISSUE THREAD

**Issue by felipepmoreno** [structurizr/dotnet#78]
Hi simon, my problem is more a question than an issue. I work for a company in Brazil and we are going to use structurizr for our software architecture projects. Now we are using .NET in visual studio code to build our diagrams, but we need to run the code to update it in structurizr. Is there anyway to update the diagram when building the project without needing to run it? Like updating when saving the file or in real-time?

**Comment by simonbrowndotje** [comment]
Your program will need to execute in order to upload the workspace ... perhaps you could wire up a [post-build event](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-specify-build-events-csharp?view=vs-2019)?

**Comment by felipepmoreno** [comment]
> Your program will need to execute in order to upload the workspace ... perhaps you could wire up a [post-build event](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-specify-build-events-csharp?view=vs-2019)?

Thanks Simon, I'll try that and congratulations for the awesome job with structurizr.
