### ISSUE TITLE
Create interfaces for all main components: e.g. IPerson, ISofwareSystem

### ISSUE THREAD

**Issue by SashaPshenychniy** [structurizr/dotnet#79]
Having classes Person and SoftwareSystem sealed without public interface makes it hard to implement any kind of extensibility.

I tried to introduce the concept of UseCase (not to overload system overview diagram with all possible connections), but in order to do that it would be nice to wrap and track somehow which relationships and which entities are used in which use-cases.

I can see two possible solutions:
1. Make classes non-sealed and allow to override public methods.
2. Introduce interfaces IPerson, ISoftwareSystem etc so that it is possible to implement Decorator pattern to track which entities are used and which relations are created in scope of every use-case.

PS: I might be missing something because I'm very new to Structurizr. I love the concept, but really missing a way to group use-cases.

**Comment by simonedamico** [comment]
I ended up using decorators and interfaces because referencing elements by strings cancel all the obvious advantages of keeping arch as code

**Comment by SashaPshenychniy** [comment]
@simonedamico How did you manage to create decorators without having the interfaces? I would also love to have decorators, but ended up with just wrappers... And that's a lot of work to wrap each and every object in Structurizr domain model...

**Comment by simonedamico** [comment]
as you said I created wrapper clases / interfaces for all the entities. 
Too be honest I just recently switched to the DSL, the dot net sdk seems to be neglected compared to java and dsl

**Comment by simonbrowndotje** [comment]
I've added an FAQ about why the classes are sealed. Structurizr doesn't have the concept of a "use case", so I'd probably recommend creating your own thin wrapper around the library ... e.g. you create a `UseCase`, your library creates a `Person` and `Relationship` as required.

**Comment by SashaPshenychniy** [comment]
Thank you for detailed explanation, @simonbrowndotje - those are valid concerns. Still a bit sad though multiple teams need to spend days on creating those wrappers because there is no out-of-the box extensibility layer on top of JSON-serializable model builders. On the other hand, it has some benefits too - we are able to implement AddXXX methods so that they behave idempotently instead of returning NULLs on retry. I think issue can be closed - thanks again.

**Comment by simonbrowndotje** [comment]
A couple of suggestions for quicker options:

 - fork the repo and do a global search/replace for `sealed` (this is probably 5-10 mins of work).
 - use [Swagger Codegen](https://swagger.io/tools/swagger-codegen/) to generate a client library directly from the [OpenAPI definition](https://github.com/structurizr/json/blob/master/structurizr.yaml) (I haven't tested this, but you'll get complete freedom to do whatever you like).

If you would like to give back to the community by open sourcing your wrapper, please do let me know and I'll add a link from the README.
