### ISSUE TITLE
DynamicView with mutiple container

### ISSUE THREAD

**Issue by pellea** [structurizr/dotnet#80]
Hello,

I would like to add into a DynamicView multiple containers.

My use case is this following workflow:
- `MobileApp` uses `Api1` [container: _API_]
- `Api1` sends a message/event to `BusXxx` [container: _events_]

Why this simple scenario cannot be done?

**Comment by simonbrowndotje** [comment]
Support for this has been added to the Java client library and Structurizr DSL, and will be rolled out soon. Following this, the same functionality will be added to the .NET client library.

**Comment by simonbrowndotje** [comment]
All of the code to support this is now in this repo ... feel free to build from source and try it out. I'll release a new version on Nuget in the next week or so.

**Comment by cpl-dev** [comment]
Hello @simonbrowndotje 

First, thank you for the great work put here, it helps us a lot!

So, is there any update for the release of a new version including multiples container view?

**Comment by simonbrowndotje** [comment]
v1.0.0 is now on Nuget ... apologies, I completely forgot about this (usual story: boot Windows VM and everything wants to update/restart ... by the time it's finished, I've been sidetracked 😂)
