### ISSUE TITLE
How can I model linked workspaces via CLI?

### ISSUE THREAD

**Issue by kirchsth** [structurizr/dotnet#83]
Hello @simonbrowndotje, 

I defined solution specific workspace models via CLI.

How can/should I model these workspace links in the overall system landscape CLI model like in your sample?
https://structurizr.com/help/workspace-linking

Thank you and best regards
Helmut

PS.: You could add an [octagon](https://github.com/plantuml-stdlib/C4-PlantUML/issues/145#issuecomment-835929388) shape, additional  to the new diamond shape ;-)

**Comment by simonbrowndotje** [comment]
Workspace linking is only supported for workspaces created via the UI. If you're using code or the DSL, you don't need that feature: 

- With the .NET library you'd just reuse code or extend a workspace (load the JSON of a base workspace, add more elements, etc).
- With the DSL you'd do the same with includes ([example](https://github.com/structurizr/cli/tree/master/examples/big-bank-plc)) or [the new workspace extension feature](https://twitter.com/simonbrown/status/1392424140980826113).

(I would need to block out a couple of hours to figure out the maths of drawing SVG octagons ... that's how long the hexagon took 😂)

**Comment by kirchsth** [comment]
Thank you for clarification I found the problem in my idea. I thought the link would offer a transformation too (e.g. team1 produces a SystemA and team2 integrates this system as component in its SystemB) but if team2 combine other systems then it combines only components of existing systems and not the existing systems.
