### ISSUE TITLE
Exporting/embedding private workspace diagrams

### ISSUE THREAD

**Issue by SbiCA** [structurizr/dotnet#84]
First of all thanks for this great piece of software ❤️ 

Could you add an api that allows exporting diagrams or embedded diagrams to external markdown. 
My use case is that my team(s) use AZ DevOps wiki as the source of truth therefore having the diagrams up to date is crucial since this is the main connection point of dev, arch and stakeholders.

At the moment I only the see the way of manually exporting the diagrams via the web page or am I missing something.

Cheers

**Comment by simonbrowndotje** [comment]
Thanks! If you're referring to diagrams produced by the Structurizr cloud service, those diagrams are rendered in the web browser, so your export options are:

- Manually via your web browser.
- Automatically via web browser automation (there are some [Puppeteer scripts](https://github.com/structurizr/puppeteer) that can assist)

There is also a paid [PNG embed feature](https://structurizr.com/help/embed-image) provided by the service.

Alternatively, you can export your workspace to a JSON file, use the [Structurizr CLI](https://github.com/structurizr/cli/blob/master/docs/export.md) to export the diagrams to PlantUML, Mermaid, DOT, etc ... and then to PNG files via those toolchains.

**Comment by SbiCA** [comment]
Thanks for the quick update I'll give the pupeteer scripts a try. 

It seems that you don't support embedding with private workspaces at the least it states `Please note that this feature is not available for private workspaces or client-side encrypted workspaces.` or is it just out of date?

**Comment by simonbrowndotje** [comment]
Apologies, that should read, "private workspaces without the sharing link enabled" (i.e. you'll need to enable the sharing link for your workspace).
