### ISSUE TITLE
Terraform support

### ISSUE THREAD

**Issue by SbiCA** [structurizr/dotnet#85]
Did you think about adding support for terraform for instance such as https://github.com/cycloidio/inframap

This would be a nice addition rather than handcrafting deployment diagrams to extract the "nodes" and structure from a external graph and map them to the logical elements of the structurizr model.

In pseudo code
``` c#
var myTfStateImporter = new TfStateImporter("local.tfstate", workspace);
myTfStateImporter.ImportInfrastrucutre(softwareSystem);

// attach container to resource in tf
myTfStateImporter.Attach(webApplication, "azurerm_app_service.myappservice");

// not sure if the importer should create the view
myTfStateImporter.CreateDeploymentView("key", "description");

```

**Comment by simonbrowndotje** [comment]
I have no plans to add this myself, but it would certainly make a nice community addition.

**Comment by rogeruiz** [comment]
@simonbrowndotje hi. What's the preferred way of adding something like this? I'm not super familiar with the .NET project under the Structurizr org. I'm looking to build out a Tree-sitter parser for the Structurizr DSL and want to get your input of what is the best approach here?

[=> Tree-sitter Introduction](https://tree-sitter.github.io/tree-sitter/)

My ultimate goal here is to be able to parse Terraform files and convert them to rudimentary DSL files written in Structurizr-DSL that can then be used to aid adoption of the C4 model for teams who are interested but are concerned with yet-another-tool.

I am so thankful for the C4 Model and for Structurizr as an open source tool and SaaS. I'm looking to contribute to your OSS projects and aid in the adoption of leveraging Structurizr and the C4 Model for Diagrams as Code (DGaC) for broader software-authoring teams. I have a small roadmap to help make working with the `structurizr/cli` a much smoother developer experience. But that's certainly for another time/issue/etc.

[=> My "small roadmap"](https://github.com/rogeruiz/scuttle/issues/7)

thanks! 
- rsr

**Comment by simonbrowndotje** [comment]
I'd probably do something like this -> https://github.com/structurizr/dsl/tree/master/docs/cookbook/dsl-and-code ... where you craft up a basic model with the DSL, then add to it via one of the client libraries (see the "Other languages" section on that page). I certainly wouldn't recommend (1) building a DSL parser in .NET or (2) parsing Terrform and generating Structurizr DSL. Feel free to join the [Slack group](https://join.slack.com/t/structurizr/shared_invite/enQtMzkyMjY1NzMwNTkzLTcyOGI1MTZmNDQwMDQ5YmZlMThiYmU1ZTM2ZWZiMzYwMjVhNmM0OWIwNjFlZTM1YmY3YzU0ZDY2MTA1YTk5Mjg) - somebody may have done something like this already.
