### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by ketevan-b** [structurizr/dotnet#89]
On 2019 we bought structurizr 
![image](https://user-images.githubusercontent.com/61318524/142011465-14bcb25c-a1c8-4388-b47c-71a1b2cd3a2d.png)
Based on this invoice, do I need to purchase only the second part in 2022 or do I need anything else?

**Comment by simonbrowndotje** [comment]
Yes, it's just the second line item (support and updates).

**Comment by ketevan-b** [comment]
Thank you very much :)
