### ISSUE TITLE
Any chance for a dsl parser in c#?

### ISSUE THREAD

**Issue by jlandgraf** [structurizr/dotnet#90]
Hi,

I am stuck to c#, so I am looking at this library. However, I did not spot a dsl-parser yet, only a json parser.
Is it available in c#?
If not, are there plans to add it?

**Comment by simonbrowndotje** [comment]
No plans to port the DSL parser I'm afraid. You can use both in combination though. The [cookbook shows an example of this with Java](https://github.com/structurizr/dsl/tree/master/docs/cookbook/dsl-and-code), but you can do a similar thing with .NET ... use the CLI tooling to convert a DSL definition into JSON, then parse the JSON via the .NET library and append to it using C# code.
