### ISSUE TITLE
Please make the archive-file optional

### ISSUE THREAD

**Issue by jlandgraf** [structurizr/dotnet#91]
Hi,

I am integration the client with a web-application. This works like clockwork, however, I do have an issue security wise by writing the archive file. to be honest, I am not interested in the file, because I am creating it myself anyways.

**Comment by simonbrowndotje** [comment]
You can set the `WorkspaceArchiveLocation` property of your `StructurizrClient` instance to be null, which will disable the archive -> https://github.com/structurizr/dotnet/blob/master/Structurizr.Client/Api/StructurizrClient.cs#L358

**Comment by jlandgraf** [comment]
besides I am slow today, you are quite right.
However, I would like to have default to be null  :)
