### ISSUE TITLE
QUESTION: Will DSL be supported, will PutWorkspace keep working when workspace is deprecated?

### ISSUE THREAD

**Issue by StijnVA** [structurizr/dotnet#92]

**Comment by simonbrowndotje** [comment]
I'm not sure what you're asking, but there are no plans to implement a DSL parser in the .NET library. Possible duplicate of #90?

**Comment by StijnVA** [comment]
If you use PutWorkspace it creates a workspace (as you might expect). I am worried about this message you get if you open it online. It suggest to migrate to DSL. If you look at the DSL editor. It shows an empty model.

![image](https://user-images.githubusercontent.com/5576173/151782183-932605bc-781d-4a29-8064-c00a384b9715.png)

**Comment by simonbrowndotje** [comment]
That's for the [online workspace editor](https://structurizr.com/help/workspace-editor) that allows people to create a workspace via a web-based UI. The .NET library is not changing and, if you're using the .NET library to create your workspace, you will not need to use that page.
