### ISSUE TITLE
the uploaded workspace of 0.54MB exceeds the size limit of 0.50MB

### ISSUE THREAD

**Issue by santo2** [structurizr/dotnet#94]
Hi,
Is there a way to make it possible to exceed the standard 0.5MB of a workspace? Having to split up into multiple workspace would mean that we need to duplicate systems, containers and relations, so this doesn't feel like something we want to do.

**Comment by simonbrowndotje** [comment]
The 0.5MB size is a limitation of the free account; a paid account increases this limit to 5MB (see https://structurizr.com/help/workspaces for more).

**Comment by santo2** [comment]
thanks for the fast feedback, I was actually thinking we were using a paid subscription :-) so I'll have to check with the one who created it

**Comment by santo2** [comment]
Found it, I was using one workspace under free subscription on my board, but I do see others that are under cloud subscription. Thanks
