### ISSUE TITLE
Relationship between Person and Container not showing

### ISSUE THREAD

**Issue by woutervanranst** [structurizr/dotnet#97]
Why is the diagram outputted by the DSL different as with the dotnet interface?
I'm (only) talking about the arrow between a and b

## DSL
```
workspace "ws" "desc" {

model {
        a = person "a"

        b = softwareSystem "b" {
            c = container "c" {
            }
        }
        
        a -> c "Uses"
    }

    views {
        systemContext b {
            include *
            autolayout
        }
    }
}
```

Output
<img width="687" alt="image" src="https://user-images.githubusercontent.com/6490925/175106081-4cefb6d4-c4ee-4cb4-a0eb-caa031ce27aa.png">

## dotnet
```
var workspace = new Structurizr.Workspace("ws", "desc");
var model = workspace.Model;

var a = model.AddPerson("a");

var b = model.AddSoftwareSystem("b");
var c = b.AddContainer("c");

a.Uses(c, "Uses");

var viewSet = workspace.Views;
var v = viewSet.CreateSystemContextView(b, "b", "descr");
v.AddAllElements();
v.EnableAutomaticLayout();
```

Output
<img width="891" alt="image" src="https://user-images.githubusercontent.com/6490925/175105833-8eef2f4a-f0a5-4816-b4f2-10edaa4a37d2.png">

**Comment by woutervanranst** [comment]
I did the diff of the resulting jsons - not that it gives more clues it just confirms that there is no relationship there to be seen (ie it is not a rendering issue)

![image](https://user-images.githubusercontent.com/6490925/175245618-cd864628-8080-4e57-924f-421b87088478.png)

**Comment by simonbrowndotje** [comment]
This will likely be the implied relationships functionality, which is enabled by default on the DSL, but not with the .NET library ... see https://github.com/structurizr/dotnet/blob/master/docs/implied-relationships.md for more.

**Comment by woutervanranst** [comment]
Brilliant! That seems highly likely. I ll check it and revert/close close the issue.

**Comment by woutervanranst** [comment]
Works! Thanks @simonbrowndotje! Keep up the good work :)
