### ISSUE TITLE
Control RelationshipStyle on Dynamic View

### ISSUE THREAD

**Issue by woutervanranst** [structurizr/dotnet#98]
Hi, I want to model the synchronous and asynchronous relationships that exist between components.
eg. container 1 makes synchronous calls to container 2, but they also interact through kafka

On a ContainerView (or the other 'regular' views) I can do that if the descriptions are different.
On a DynamicView it seems the line style is determined by the first relationship that was added in the model -- is there a way to control this on an interaction-by-interaction basis?

## Expected: as on a ContainerView
```
var a = model.AddSoftwareSystem("a");
var c1 = a.AddContainer("c1");
var c2 = a.AddContainer("c2");

var r1 = c1.Uses(c2, "Uses Sync", "", Structurizr.InteractionStyle.Synchronous); // this line style will be used in the dynamic view
var r2 = c1.Uses(c2, "Uses Async", "", Structurizr.InteractionStyle.Asynchronous);
    
var viewSet = workspace.Views;
var v1 = viewSet.CreateContainerView(a, "b", "descr");
v1.AddAllElements();
v1.EnableAutomaticLayout();

var styles = viewSet.Configuration.Styles;
styles.Add(new Structurizr.RelationshipStyle(Structurizr.Tags.Synchronous) { Dashed = false });
styles.Add(new Structurizr.RelationshipStyle(Structurizr.Tags.Asynchronous) { Dashed = true });
```

<img width="315" alt="image" src="https://user-images.githubusercontent.com/6490925/180383765-8638c28e-c7bf-47ac-9603-3a95d34a17d6.png">

## Actual on Dynamic View (1)
```
var v2 = viewSet.CreateDynamicView(a, "b-dynamic", "");
v2.Add(c1, "sync", c2);
v2.Add(c1, "async", c2);
// no way to control line style, line style will be the RelationshipStyle of the first relationship added between these components
```

<img width="276" alt="image" src="https://user-images.githubusercontent.com/6490925/180385317-88bd571e-97b6-4677-b7e0-20fa56683021.png">

## Actual on Dynamic View (2)
```
var v2 = viewSet.CreateDynamicView(a, "b-dynamic", "");
v2.Add(r1);
v2.Add(r2); // yields an InvalidOperationException ("Failed to compare two elements in the array.") on PutWorkspace
```

**Comment by simonbrowndotje** [comment]
You'll now be able to do this, to explicitly specify a particular relationship:

```
var v2 = viewSet.CreateDynamicView(a, "b-dynamic", "");
v2.Add(r1, "sync");
v2.Add(r2, "async");
```
