### ISSUE TITLE
Include mode on Filtered Views not working

### ISSUE THREAD

**Issue by nwright1** [structurizr/dotnet#99]
Hi,

When generating a filtered view using the Include FilterMode, the json omitted does not contain the FilterMode property:

![image](https://user-images.githubusercontent.com/12471422/185809437-430f6a12-a12d-49d5-9759-f1cf2bb08e21.png)

When viewed in Structurizr Lite this is treated as Exclude instead of Include and the diagram does not render correctly, which can be seen when the json is updated by Structurizr Lite:
![image](https://user-images.githubusercontent.com/12471422/185809513-c9ff97b1-1349-4b47-b8a0-0aa0b8f9cfbf.png)

Is this a bug in the implementation of Structurizr .NET or Structurizr Lite?

**Comment by simonbrowndotje** [comment]
It's a bug in the Structurizr for .NET library ... thanks!
